// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Post struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	PostedBy  string
	Body      string
	Likes     int32
	Views     int32
}

type Report struct {
	ID         uuid.UUID
	ReportedAt time.Time
	ReportedBy string
	Reason     string
}
