// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: posts.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (id, created_at, updated_at, posted_by, body, views, likes)
VALUES (
   $1,
   NOW(),
   NOW(),
   $2,
   $3,
   $4,
   $5
) RETURNING id, created_at, updated_at, posted_by, body, likes, views
`

type CreatePostParams struct {
	ID       uuid.UUID
	PostedBy string
	Body     string
	Views    int64
	Likes    int64
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.ID,
		arg.PostedBy,
		arg.Body,
		arg.Views,
		arg.Likes,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PostedBy,
		&i.Body,
		&i.Likes,
		&i.Views,
	)
	return i, err
}
