// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: reports.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const reportPost = `-- name: ReportPost :one
INSERT INTO reports (id, reported_at, reported_by, reason)
VALUES (
   $1,
   NOW(),
   $2,
   $3
) RETURNING id, reported_at, reported_by, reason
`

type ReportPostParams struct {
	ID         uuid.UUID
	ReportedBy string
	Reason     string
}

func (q *Queries) ReportPost(ctx context.Context, arg ReportPostParams) (Report, error) {
	row := q.db.QueryRowContext(ctx, reportPost, arg.ID, arg.ReportedBy, arg.Reason)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReportedAt,
		&i.ReportedBy,
		&i.Reason,
	)
	return i, err
}
