// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const getSubscribers = `-- name: GetSubscribers :many
SELECT subscribers FROM users
WHERE id = $1
`

func (q *Queries) GetSubscribers(ctx context.Context, id uuid.UUID) ([][]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getSubscribers, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]uuid.UUID
	for rows.Next() {
		var subscribers []uuid.UUID
		if err := rows.Scan(pq.Array(&subscribers)); err != nil {
			return nil, err
		}
		items = append(items, subscribers)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
